# Generated by Django 5.2.5 on 2025-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
